{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToStartCallback"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":2,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/reachabilitymonitor\/reachabilityerror\/failedtostartcallback(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/ReachabilityMonitor\/documentation\/ReachabilityMonitor\/ReachabilityError\/failedToStartCallback(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An error indicating the reachability callback could not be configured"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToStartCallback"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"title":"ReachabilityError.failedToStartCallback(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:19ReachabilityMonitor0A5ErrorO21failedToStartCallbackyACs5Int32VcACmF","modules":[{"name":"ReachabilityMonitor"}]},"hierarchy":{"paths":[["doc:\/\/ReachabilityMonitor\/documentation\/ReachabilityMonitor","doc:\/\/ReachabilityMonitor\/documentation\/ReachabilityMonitor\/ReachabilityError"]]},"references":{"doc://ReachabilityMonitor/documentation/ReachabilityMonitor":{"role":"collection","title":"ReachabilityMonitor","abstract":[],"identifier":"doc:\/\/ReachabilityMonitor\/documentation\/ReachabilityMonitor","kind":"symbol","type":"topic","url":"\/documentation\/reachabilitymonitor"},"doc://ReachabilityMonitor/documentation/ReachabilityMonitor/ReachabilityError":{"role":"symbol","title":"ReachabilityError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReachabilityError"}],"abstract":[{"type":"text","text":"Errors that could cause a "},{"type":"codeVoice","code":"ReachabiltiyMonitor"},{"type":"text","text":" to fail"}],"identifier":"doc:\/\/ReachabilityMonitor\/documentation\/ReachabilityMonitor\/ReachabilityError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReachabilityError"}],"url":"\/documentation\/reachabilitymonitor\/reachabilityerror"},"doc://ReachabilityMonitor/documentation/ReachabilityMonitor/ReachabilityError/failedToStartCallback(_:)":{"role":"symbol","title":"ReachabilityError.failedToStartCallback(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToStartCallback"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"An error indicating the reachability callback could not be configured"}],"identifier":"doc:\/\/ReachabilityMonitor\/documentation\/ReachabilityMonitor\/ReachabilityError\/failedToStartCallback(_:)","kind":"symbol","type":"topic","url":"\/documentation\/reachabilitymonitor\/reachabilityerror\/failedtostartcallback(_:)"}}}